rootUrl: 'http://localhost:3000/components/preview/'
gridUrl: 'http://127.0.0.1:4444/wd/hub'
screenshotsDir: './test/visual/screens'
calibrate: false
tolerance: 3.5
windowSize: 1600x1080

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome
