language: node_js
node_js:
  - "6"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=test:webdriver

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick
  artifacts:
    paths:
      - $TRAVIS_BUILD_DIR/test/screenshots/diff/
      - $TRAVIS_BUILD_DIR/test/errorShots/
  sauce_connect: true

cache:
  apt: true
  yarn: false
  directories:
    - node_modules

install:
  - npm install
  - npm run dist

script:
  - npm run $TEST_SUITE # run unit test, css regression, and css reference in parallel
