language: node_js

env:
  global:
    - CXX=g++-4.8

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  yarn: false
  directories:
    - node_modules

matrix:
  include:
    # Nodejs 6 - Webdriver.io
    - node_js: 6
      env: TEST_SUITE=test:webdriver
      addons:
        apt:
          packages:
            - graphicsmagick
        sauce_connect: true
      artifacts:
        paths:
          - $TRAVIS_BUILD_DIR/test/screenshots/diff/
          - $TRAVIS_BUILD_DIR/test/errorShots/

    # Nodejs 6 - Lint
    - node_js: 6
      env: TEST_SUITE=lint

install:
  - npm install

before_script:
  - npm run dist

script:
  - npm run $TEST_SUITE
