language: node_js
node_js: 6

env:
  global:
    - CXX=g++-4.8

sudo: false
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  yarn: false
  directories:
    - node_modules

matrix:
  include:
    - env: TEST_SUITE=test:webdriver
      addons:
        apt:
          packages:
            - graphicsmagick
      artifacts:
        paths:
          - $TRAVIS_BUILD_DIR/test/screenshots/diff/
          - $TRAVIS_BUILD_DIR/test/errorShots/
      sauce_connect: true

    # Node 4 without GraphicsMagick
    - env: TEST_SUITE=lint

install:
  - npm install
  - npm run dist

script:
  - npm run $TEST_SUITE
