language: node_js
node_js:
  - "6"
env:
  global:
    - CXX=g++-4.8
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=test:a11y
    - TEST_SUITE=gemini:test

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
  artifacts:
    s3_region: "eu-west-2"
    debug: true
    paths:
      - $TRAVIS_BUILD_DIR/gemini-report/
  sauce_connect: true

cache:
  apt: true
  yarn: false
  directories:
    - node_modules

install:
  - npm install
  - npm run dist

before_script:
  - npm install -g selenium-standalone
  - selenium-standalone install
  - sleep 5

script:
  - npm run $TEST_SUITE # run tests in parallel
